"""Copyright 2022 Google LLC.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Annotator P-Value Experimentation Suite.

Run args:
  --n_items: Number of items.
  --k_responses: Number of responses per item. Must be no greater than number
        of responses per items in the input_data dataset.
  --line_num: Line of configuration file to run, or (default) -1 for all lines.
  --exp_dir: Path to experiment directory for input, configuration, and output
        files.
  --config_file: Filename of configuration parameters for running experiments.
  --input_response_file: Filename containing responses generated by
      parameterized_sample over which to run simulation.
"""

import datetime
import os
import random as rand

from absl import app
from absl import flags
from absl import logging
import parameterized_sample_lib as psample
import response_resampler_lib as resampler_lib

_N_ITEMS = flags.DEFINE_integer("n_items", 100, "Number of items.")
_K_RESPONSES = flags.DEFINE_integer(
    "k_responses",
    5,
    "Number of responses per item. Must be no greater than "
    "number of responses per items in the input_data dataset.",
)
_LINE_NUM = flags.DEFINE_integer("line_num", -1, "Line of config file.")
_CONFIG_FILE = flags.DEFINE_string(
    "config_file",
    "config_N=1000_K=5_n_trials=1000.csv",
    "Config file for running experiments located in exp_dir/config/.",
)
_INPUT_RESPONSE_FILE = flags.DEFINE_string(
    "input_response_file",
    "responses_simulated_distr_dist=0.3_gen_N=1000_K=5_num_samples=1000.json",
    "File name in <exp_dir> containing the output of parameterized_sample to"
    "resample from.",
)
_EXP_DIR = flags.DEFINE_string(
    "exp_dir",
    "/tmp/ptest/",
    "Path name to experiment directory.",
)
_USE_PICKLE = flags.DEFINE_boolean(
    "use_pickle",
    False,
    "If true load the data using pickle. Otherwise load using json."
    "Pickle is much faster as it saves the data in binary format.",
)
_RANDOM_SEED = flags.DEFINE_integer(
    "random_seed",
    None,
    "When set, it generates the data in deterministically across runs.",
)

def main(_):
  # Set random seeds for deterministic data generation.
  if _RANDOM_SEED.value:
    rand.seed(_RANDOM_SEED.value)

  exp_dir = _EXP_DIR.value
  input_response_file = _INPUT_RESPONSE_FILE.value
  n_items = _N_ITEMS.value
  k_responses = _K_RESPONSES.value
  config_file = _CONFIG_FILE.value
  config_line_num = _LINE_NUM.value

  logging.info(
      "Running ptest experiments with command line arguments:"
      "n_items = %d, k_responses = %d, "
      "line_num = %d, config_file = %s, "
      "input_response_file = %s",
      n_items,
      k_responses,
      config_line_num,
      config_file,
      input_response_file,
  )

  data_file = os.path.join(exp_dir, input_response_file)
  logging.info("Opening data file %s", data_file)
  start_time = datetime.datetime.now()
  response_sets = psample.read_samples_from_file(data_file, _USE_PICKLE.value)
  loading_time = datetime.datetime.now() - start_time
  logging.info(
      "Finished loading file. Loading time=%f", loading_time.total_seconds()
  )

  # Reduce the size for all the data arrays in response_data if the
  # response examples are over-generated.
  response_sets.truncate(n_items, k_responses)

  line_str = "" if config_line_num == -1 else f"_line={config_line_num}"
  file_name = (
      f"results_N={n_items}_K={k_responses}_{input_response_file}{line_str}.csv"
  )
  output_file_path = os.path.join(exp_dir, file_name)
  config_file_path = os.path.join(exp_dir, "config/", config_file)

  experiments_manager = resampler_lib.ExperimentsManager(
      response_sets,
      config_file_path,
      config_line_num,
      k_responses,
      output_file_path,
  )

  logging.info("Experiments set up. Getting ready to run.")
  experiments_manager.run_experiments()

if __name__ == "__main__":
  app.run(main)
